name: product_catalog
extraction:
  type: parquet
  source: data/raw/products.parquet
  options: {} # FIXME: The user should be able to not pass an empty options dict
exportation:
  type: csv
  destination: data/processed/products_processed.csv
  options: {} # FIXME: The user should be able to not pass an empty options dict
