name: sales
extraction:
  type: csv
  source: data/raw/sales.csv
  options:
    delimiter: ","
    encoding: "utf-8"
exportation:
  type: csv
  destination: data/processed/sales_processed.csv
  options: {} # FIXME: The user should be able to not pass an empty options dict
