name: sales
extraction:
  type: csv
  source: data/raw/sales.csv
  options:
    delimiter: ","
    encoding: "utf-8"
transformations:
  - type: rename_columns
    params:
      mapping:
        "product": "product_id"
        "quantity_sold": "quantity"
exportation:
  type: csv
  destination: data/processed/sales_processed.csv
  options: {} # FIXME: The user should be able to not pass an empty options dict
